import Head from 'next/head';

import cx from 'classnames';
import { getLayout } from '~shared/layouts/main-layout';

import styles from '~shared/styles/Home.module.scss';
import { Link } from '~shared/ui';

// eslint-disable-next-line import/no-default-export
export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Link href="/" activeClassName="">
          <a
            className={cx([styles.area, styles.left])}
            style={{
              backgroundColor: 'rgba(177, 177, 177, 0.2)',
            }}
          >
            <span>Читать книгу</span>
          </a>
        </Link>

        <span className={styles.separator}>или</span>

        <Link href="/" activeClassName="">
          <a
            className={cx([styles.area, styles.right])}
            style={{
              backgroundColor: 'rgba(196, 196, 196, 0.2)',
            }}
          >
            <span>Атмосфера</span>
          </a>
        </Link>
      </div>
    </>
  );
}

HomePage.getLayout = getLayout;
